### ISSUE TITLE
Add support for Android 9

### ISSUE THREAD

**Issue by duramato** [kitsunyan/foxy-boot#1]
Just like the title, I'd like to request, if possible, support for Android 9

**Comment by kitsunyan** [comment]
Unfortunately, boot animation can't be replaced with Magisk starting from Android 8, and it can't be replaced on Android 9 as well. It's possible to fix the binary itself, but I can't do anything with Magisk.

**Comment by zzndb** [comment]
Is there anyway to create a non-magisk module to implement this such as normal flash zip or a substratum theme?

**Comment by char101** [comment]
I replaced the bootanimation (OP6 pie) in twrp, but ldcheck failed

```
OnePlus6:/system/bin # ./bootanimation ldcheck
CANNOT LINK EXECUTABLE "./bootanimation": cannot locate symbol "_ZN7android21SurfaceComposerClient22closeGlobalTransactionEb" referenced by "/system/bin/bootanimation"...
```

So the problem is not only magisk boot timing.

Here is the steps if you want to replace it in recovery

```
adb reboot recovery
twrp: mount system
adb push bootanimation-arm64-v8a /system/system/bin/
adb shell
    cd /system/system/bin
    mv bootanimation bootanimation.orig
    mv bootanimation-arm64-v8a bootanimation
    chown 0:2000 bootanimation
    chmod 755 bootanimation
    chcon u:object_r:bootanim_exec:s0 bootanimation
twrp: reboot
```

**Comment by kitsunyan** [comment]
> Is there anyway to create a non-magisk module to implement this such as normal flash zip or a substratum theme?

Bootanimation requires access to the kernel ring buffer, which is not available from `bootanim` domain, so I'm [patching](https://github.com/kitsunyan/foxy-boot/blob/278438a5f6dc0f60531f8ba8819e78e0d1de009b/magisk/common/service.sh) the selinux policy to allow this. Apart from that, nothing stops you from simple copy-pasting the binary to `/system/bin/bootanimation` and setting matching permissions/context to make it work.

> So the problem is not only magisk boot timing.

That's right. I already [reported](https://github.com/Magisk-Modules-Repo/submission/issues/279#issuecomment-482461516) that it doesn't work on Android 9. It's not that easy to fix this problem since my boot animation uses private Android API, so it's important to keep using just simple method calls to reduce the risks of ABI incompatibility.

The way of handling surface flinger transactions has changed in Android 9, making it uneasy to implement new mechanism following the principle described above. And I decided to put this problem aside since boot animation will not work when installed via Magisk for other (and more important) reasons.

I'll try to investigate what can I do with this later so advanced users could install it manually and use it without Magisk.

**Comment by zzndb** [comment]
> nothing stops you from simple copy-pasting the binary to `/system/bin/bootanimation` and setting matching permissions/context to make it work.

:joy:  I'd just build the zip file, following the install.sh file put the binary file. And get the same error like the bro above :smile: 

> I'll try to investigate what can I do with this later so advanced users could install it manually and use it without Magisk.

expecting ...

**Comment by kitsunyan** [comment]
https://github.com/kitsunyan/foxy-boot/commit/c51f18d7fa5654486fe63e994283ef56388e6551 should fix ABI compatibility. Still can't be installed via magisk, further discussion regarding magisk compatibility should be done [there](https://github.com/kitsunyan/foxy-boot/issues/2).
