### ISSUE TITLE
sepolicy override not working on Nougat

### ISSUE THREAD

**Issue by Ristovski** [kitsunyan/foxy-boot#3]
Bootanimation is blank. Running `dmesg|grep bootanim` shows many instances of:
```
type=1400 audit(1555524097.527:955): avc: denied { syslog_read } for uid=1003 pid=610 comm="bootanimation" scontext=u:r:bootanim:s0 tcontext=u:r:kernel:s0 tclass=system permissive=0
```

Which indicates `bootanimation` is not getting the `syslog_read` permission.

Using Magisk v18.1. Perhaps an issue with the `service.sh`?

Device is Moto G5 Plus running LineageOS 14.1.

Can provide further details if needed.

**Comment by kitsunyan** [comment]
Can you check Magisk log? There should be a line containing `foxy-boot: exec [service.sh]`.

Can you run `magiskpolicy --live 'allow bootanim kernel system syslog_read'` manually and then `stop` and `start` to restart zygote and surfaceflinger, thus displaying the bootanimaion again? It would be better to run these commands from adb instead of terminal emulator application, since all applications will be stopped after `stop` command, although you can run something like `(stop; sleep 1; start) &`.

**Comment by Ristovski** [comment]
`foxy-boot: exec [service.sh]` was indeed present inside the Magisk log.

After running that command manually (which required root permissions), the bootanimation output did indeed show up.

Maybe the `magiskpolicy` is not being run as root?

**Comment by kitsunyan** [comment]
All init scripts from magisk dir are executed from `u:r:magisk:s0`, so I doubt there is policy issue. But it might be possible `service.sh` is executed too late (even _after_ bootanimation). Can you also check script execution time (it's written to Magisk log) and bootanimation start/end time?

You can also check the execution time of other scripts (both your scripts (which are executed before module scripts) and other module scripts).

In the worst case you can try to create `/sbin/.magisk/img/.core/post-fs-data.d/foxy-boot.sh` and add the same line there (but I think it's a bad idea since `magiskpolicy` is very slow, and post-fs-data scripts are limited to 10 seconds).

**Comment by Ristovski** [comment]
Interestingly enough, Magisks log reports the wrong time/date until after the service scripts are run, this makes getting timing info a pain.

I did test the `post-fs-data.d` approach and it does not work.

`dmesg` reports `avc` denies for `syslog_read` 9.3s into the boot, up until 24.9s into the boot.

I will try getting the bootanimation start vs foxy-boot timing later.

**Comment by kitsunyan** [comment]
> Interestingly enough, Magisks log reports the wrong time/date until after the service scripts are run, this makes getting timing info a pain.

Same to me. It might be something qualcomm-specific, the valid time is not set immediately on boot but something named `QC-time-services` in log is responsible for setting it later.

You can try to connect the phone to PC, reboot it and run something like `while sleep 1; do adb shell logcat && break; done > logcat.txt` so you'll be more lucky to calculate timing. Magisk prints all logs there as well, so you might be able to compare bootanimation start time (the time when audit will spit `syslog_read` permission errors) right there.

> I did test the post-fs-data.d approach and it does not work.

That's really strange. Actually, it's normal that bootanimation doesn't show anything first ~2 seconds since `service.sh` is started after bootanimation. But when I put the same script to `post-fs-data.d`, it starts to print messages immediately. `post-fs-data` scripts are executed _before_ magic mount, which will copy bootanimation to /system/bin, so `post-fs-data`-script should definitely alter sepolicy before bootanimation starts.. However, it's not your case, which makes me think there might be something wrong with my `service.sh`.

How many `syslog_read` messages are you seeing in `dmesg`?

**Comment by Ristovski** [comment]
> How many `syslog_read` messages are you seeing in `dmesg`?

```
# dmesg | grep bootanimation | grep syslog_read | wc -l
403
```

Now the interesting part:
I can find  `04-18 21:55:42.911   437   652 I Magisk  : foxy-boot: exec [service.sh]`
in the log shown in the Magisk Manager, but I can't find that line in the logcat. All other instances where other modules `exec` their `service.sh` are (I think) present in the logcat.

Doesn't matter, could be irrelevant. I pulled the `magisk.log` from `/cache` :)

All other modules in the log report `exec`ing their `service.sh` on the wrong date (`02-27`), while foxy-boot is the only module that runs it's `service.sh` in the correct timedate (`04-18`) (as shown above), example (they do execute one right after the other, not snipped):

```
02-27 08:18:42.034   437   652 I Magisk  : crokrammgmtfix: exec [service.sh]
04-18 21:55:42.911   437   652 I Magisk  : foxy-boot: exec [service.sh]
```

The first correct timedate deny occurs at `04-18 21:55:13.533` and the last at `04-18 21:55:34.796`.

There are only two denies that happen in the wrong datetime, and both happen at `02-27 08:18:41.886`

If we consider the first correct timedate deny at `21:55:13`, foxy-boot execs it's `service.sh` at `21:55:42`, which is 29 seconds late. Considering the last deny happens at `21:55:34`, it indeed appears that it's too late.

**Comment by kitsunyan** [comment]
> 403

I just wanted to make sure boot animation doesn't stuck at `klogctl` for some reason.

Nice, your report reveals the reason. I already faced a similar problem before. [It's said in docs](https://github.com/topjohnwu/Magisk/blob/be7e73725342cf7af17b4c7198abf412737da589/docs/guides.md) that `service.d` scripts are executed in parallel with the system, but __not in parallel with each other__. They're still executed one by another, like `post-fs-data.d` scripts.

And now let's look at `crokrammgmtfix` module source code whose `service.sh` was execute before `foxy-boot`:
https://github.com/Magisk-Modules-Repo/crokrammgmtfix/blob/b4d9870056bcb9e2014498f21de4249857b787c5/common/service.sh#L11-L12

> PS: Still no idea why the post-fs-data does not work, I just copied the script over and renamed it to foxy-boot.sh, do I need to do anything else?

I just wanted to advice to check permissions, but you've edited the commit while I wrote my own.

**Comment by Ristovski** [comment]
Sorry for the edits :)

It works nicely now that `post-fs-data` works, and making it fork makes it not block the boot process.

Maybe you can switch to `post-fs-data` but make the command fork like I did?

**Comment by kitsunyan** [comment]
> Maybe you can switch to post-fs-data but make the command fork like I did?

I didn't read the source code of `magiskpolicy`, but the fact it takes this much time (>1000ms on my Sony Z5) makes me think that policy update process is not atomic. `post-fs-data.d` scripts are limited to 10 seconds (in sum), so if every module developer will fork their scripts and alter the policy this way, there might be race conditions.

On the other hand, I don't have neither power nor motivation to convince all module developers to fork their long-running `service.d` processes (unless the're do something atomic)..

I think I can add a notice in documentation, I really don't like the idea of forking in `post-fs-data.d` script.

**Comment by Ristovski** [comment]
Understandable. 

Considering `crokrammgmtfix` sleeping for 30s being the (local) issue here, closing!

**Comment by Ristovski** [comment]
fwiw, `crokrammgmtfix` fixed it https://github.com/Magisk-Modules-Repo/crokrammgmtfix/commit/d68cae403d4dde1a24fcbfc50ee43e63f39d8714

**Comment by kitsunyan** [comment]
Nice to see that!
